"""PiPER + lift desk debugging. Mounted clamps are a locked installation snapshot."""
from pathlib import Path
import argparse,json,time
parser=argparse.ArgumentParser();parser.add_argument('--validate',action='store_true');args=parser.parse_args()
root=Path(__file__).resolve().parent;out=root/'evidence';out.mkdir(exist_ok=True)
from isaacsim import SimulationApp
app=SimulationApp({'headless':args.validate,'width':1280,'height':960,'renderer':'RayTracedLighting','extra_args':['--/renderer/multiGpu/enabled=false','--/exts/isaacsim.physics.newton/auto_switch_on_startup=false']})
import carb,omni.usd,omni.physx,omni.physics.tensors,numpy as np
from lift_controller import LiftController
ctx=omni.usd.get_context();ctx.open_stage(str(root/'scene.usda'));stage=ctx.get_stage();stage.SetEditTarget(stage.GetSessionLayer())
settings=carb.settings.get_settings();settings.set('/rtx/post/tonemap/op',4);settings.set('/rtx/post/tonemap/filmIso',200.)
from omni.kit.viewport.utility import get_active_viewport
vp=get_active_viewport()
if vp:vp.set_active_camera('/World/Camera')
import omni.replicator.core as rep
rep.orchestrator.set_capture_on_play(False)
product=rep.create.render_product('/World/Camera',(1280,960));rgb=rep.AnnotatorRegistry.get_annotator('rgb');rgb.attach([product])
for i in range(60):app.update()
sim=omni.physx.get_physx_simulation_interface();assert sim.attach_stage(ctx.get_stage_id());dt=1/480;t=0.
sim.simulate(dt,t);sim.fetch_results();t+=dt
sv=omni.physics.tensors.create_simulation_view('numpy',stage_id=ctx.get_stage_id());view=sv.create_articulation_view('/World/Desk/Joints/Anchor');control=LiftController(view)
names=list(view.shared_metatype.dof_names);print('DOFS',names,flush=True)
idx=[names.index('joint'+str(i)) for i in range(1,9)];indices=np.array([0],dtype=np.int32)
targets=view.get_dof_positions().copy();home=np.array([0,.65,-.85,0,.2,0,.02,-.02]);targets[0,idx]=home
view.set_dof_positions(targets,indices);view.set_dof_position_targets(targets,indices)
samples=[];saved=set();reference=None
if not args.validate:
 import omni.ui as ui
 window=ui.Window('PiPER and lift desk',width=410,height=450)
 with window.frame:
  with ui.VStack(spacing=6):
   ui.Label('Table height (m)');height=ui.FloatSlider(min=.635,max=1.235);height.model.set_value(.635);height.model.add_value_changed_fn(lambda m:control.set_height(m.as_float))
   sliders=[]
   for j,(lo,hi) in enumerate([(-150,150),(0,179),(-169,0),(-99,99),(-69,69),(-120,120)]):
    ui.Label('Joint '+str(j+1)+' (degrees)');slider=ui.FloatSlider(min=lo,max=hi);slider.model.set_value(float(np.degrees(home[j])));slider.model.add_value_changed_fn(lambda m,j=j:targets.__setitem__((0,idx[j]),np.radians(m.as_float)));sliders.append(slider)
   ui.Label('Gripper half opening (m)');grip=ui.FloatSlider(min=0,max=.035);grip.model.set_value(.02)
   def set_grip(m):targets[0,idx[6]]=m.as_float;targets[0,idx[7]]=-m.as_float
   grip.model.add_value_changed_fn(set_grip);readout=ui.Label('');ui.Label('Simulation runs here. Do not press timeline Play.')
while app.is_running() and (not args.validate or t<10):
 start=time.perf_counter()
 if args.validate:
  control.set_height(.715 if 1<t<6 else .635)
  targets[0,idx[0]]=.12 if 2<t<6 else 0
  targets[0,idx[6]]=.03 if 2<t<6 else .02;targets[0,idx[7]]=-targets[0,idx[6]]
 for _ in range(16):
  control.tick(dt);command=view.get_dof_positions().copy();command[0,idx]=targets[0,idx]
  # Preserve lift target generated by LiftController.
  command[:,control.joints]=(control.command-control.minimum)/2
  view.set_dof_position_targets(command,indices)
  sim.simulate(dt,t);sim.fetch_results();t+=dt
 q=view.get_dof_positions();assert np.isfinite(q).all()
 if args.validate and len(samples)<int(t*10):
  samples.append({'t':t,'height':control.measured_height(),'q':q[0].tolist(),'arm_error':float(np.max(np.abs(q[0,idx]-targets[0,idx]))),'link_poses':view.get_link_transforms()[0].tolist()})
 if not args.validate:
  omni.physx.get_physx_interface().update_transformations(False,True,False);app.update();readout.text=f'Tabletop {control.measured_height():.4f} m'
  delay=16*dt-(time.perf_counter()-start)
  if delay>0:time.sleep(delay)
 for sec,label in ([(.8,'initial'),(5.5,'raised'),(9.5,'returned')] if args.validate else []):
  if t>=sec and label not in saved:
   omni.physx.get_physx_interface().update_transformations(False,True,False)
   for _ in range(12):app.update()
   rep.orchestrator.step(delta_time=0.,pause_timeline=False)
   from PIL import Image
   data=np.asarray(rgb.get_data())[:,:,:3];Image.fromarray(data).save(out/(label+'.png'));saved.add(label);print('CAPTURE',label,t,control.measured_height(),float(data.mean()),flush=True)
if args.validate:
 report={'dof_names':names,'link_names':list(view.shared_metatype.link_names),'samples':samples,'finite':True,'height_range':[min(s['height'] for s in samples),max(s['height'] for s in samples)]}
 (out/'runtime.json').write_text(json.dumps(report,indent=2));print('VALIDATION_DONE',report['height_range'],flush=True)
sim.detach_stage();app.close()
